swagger: "2.0"
info:
  description: "rest api for capplan frontend"
  version: "1.0.0"
  title: "Swagger CapPlan"
  contact:
    email: "felix.boesing@t-online.de"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
tags:
- name: "dummy"
  description: "dummy"
schemes:
- "https"
- "http"
paths:
  /dummy/dummy: