openapi: 3.0.1
info:
  title: CapPlan Analytics API
  description: Rest API for capplan analytics
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://petstore.swagger.io/v2
- url: http://petstore.swagger.io/v2
tags:
- name: capacity
  description: All functions that rely on plan FTEs for different Channels
- name: scheduling
  description: All functions for scheduling tasks and calculations
paths:
  /capacity:
    get:
components: {}
